spring.main.allow-bean-definition-overriding : true
logging:
  level:
    org:
      springframework:
        boot: INFO
    pl:
      futurecollars:
        invoicing:
          db: DEBUG
spring:
  datasource:
    url: jdbc:postgresql://localhost:5555/postgres
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

